### PR TITLE
suggested change.

### PR DESCRIPTION
**Pull request by anordin95**

### CODE REVIEW

**Review by remzi-arpacidusseau — APPROVED** [review]
changed to "We have seen the introduction of a major OS subsystem: virtual memory. The VM system is responsible for providing the illusion of a large, sparse, private address space to each running program; each virtual address space contains all of a program's instructions and data, which can be referenced by the program via virtual addresses. The OS, with some serious hardware help, will take each of these virtual memory references and turn them into physical addresses, which can be presented to the physical memory in order to fetch or update the desired information. The OS will provide this service for many processes at once, making sure to protect programs from one another, as well as protect the OS.  The entire approach requires a great deal of mechanism (i.e., lots of low-level machinery) as well as some critical policies to work; we'll start from the bottom up, describing the critical mechanisms first. And thus we proceed!" Thanks for the suggestion!

**Review by remzi-arpacidusseau — COMMENTED** [review]
eh, I think I wanted to use internal frag there and hence it kind of makes sense to me. thanks though!

**Comment by anordin95** [comment]
> "private address space to each running program; each virtual address space contains all of a program's instructions and data, which can be referenced by the program via virtual addresses"

1. Ah, excellent!

---

> "I think I wanted to use internal frag there"
  
2. Mhm that makes sense. I was more confused by the usage of "thus" than "internal fragmentation". 
Using "thus" after a sentence fragment which nearly defines "internal fragmentation" felt odd to me.
> _**restricted to placing an address space in a fixed-sized slot**_ and thus internal fragmentation can arise

I don't know the best way to re-phrase this, but perhaps something along the lines of:
> restricted to placing an address space in a fixed-sized slot. **_If the address space's size does not exactly match the slot's fixed size, there will be what's known as internal fragmentation._**

---

**Comment by remzi-arpacidusseau** [comment]
p.s. thanks! you will be ack'd in the preface too.

**Comment by remzi-arpacidusseau** [comment]
thanks again!

**Pull request merged**
